package com.libreria.sistema.config;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.assertj.core.api.Assertions.assertThat;

class InventarioSchemaInitializerTest {

    @Test
    void agregaColumnasNuevasATablaAntiguaDeDetalleInventario() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:inventario-schema-init;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        ));

        jdbcTemplate.execute("""
                CREATE TABLE detalle_toma_inventario (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    toma_inventario_id BIGINT NOT NULL,
                    producto_id BIGINT NOT NULL,
                    stock_sistema INTEGER NOT NULL,
                    stock_fisico INTEGER,
                    diferencia INTEGER,
                    contado BOOLEAN,
                    fecha_conteo TIMESTAMP,
                    observacion VARCHAR(255),
                    ajuste_aplicado BOOLEAN
                )
                """);

        new InventarioSchemaInitializer(jdbcTemplate).verificarEsquemaInventario();

        assertThat(existeColumna(jdbcTemplate, "correccion_aplicada")).isTrue();
        assertThat(existeColumna(jdbcTemplate, "segundo_conteo_requerido")).isTrue();
        assertThat(existeColumna(jdbcTemplate, "fecha_deshacer_conteo")).isTrue();
        assertThat(existeColumna(jdbcTemplate, "precio_aplicado_correccion")).isTrue();

        jdbcTemplate.update("""
                INSERT INTO detalle_toma_inventario (
                    ajuste_aplicado,
                    categoria_corregida,
                    clasificacion_corregida,
                    color_corregido,
                    contado,
                    correccion_aplicada,
                    correccion_pendiente,
                    costo_anterior_correccion,
                    costo_aplicado_correccion,
                    costo_corregido,
                    diferencia,
                    fecha_aplicacion_correccion,
                    fecha_conteo,
                    fecha_correccion,
                    fecha_deshacer_conteo,
                    fecha_primer_conteo,
                    fecha_segundo_conteo,
                    marca_corregida,
                    modelo_corregido,
                    nombre_corregido,
                    observacion,
                    precio_anterior_correccion,
                    precio_aplicado_correccion,
                    precio_corregido,
                    primer_conteo_fisico,
                    producto_id,
                    segundo_conteo_confirmado,
                    segundo_conteo_fisico,
                    segundo_conteo_requerido,
                    stock_anterior_ajuste,
                    stock_fisico,
                    stock_nuevo_ajuste,
                    stock_sistema,
                    tipo_corregido,
                    usuario_aplicacion_correccion,
                    usuario_conteo,
                    usuario_correccion,
                    usuario_deshacer_conteo,
                    usuario_primer_conteo,
                    usuario_segundo_conteo,
                    zona_conteo,
                    toma_inventario_id
                ) VALUES (
                    FALSE, 'Utiles', 'MERCADERIA', 'Azul', TRUE,
                    FALSE, FALSE, 1.0000, 1.1000, 1.1000, 0,
                    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
                    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Marca', 'Modelo', 'Lapicero',
                    'Conteo de prueba', 1.50, 1.60, 1.60, 10, 1,
                    TRUE, 10, FALSE, 10, 10, 10, 10, 'PRODUCTO',
                    'admin', 'admin', 'admin', 'admin', 'admin', 'admin', 'Mostrador', 1
                )
                """);

        Integer total = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM detalle_toma_inventario", Integer.class);
        assertThat(total).isEqualTo(1);
    }

    private boolean existeColumna(JdbcTemplate jdbcTemplate, String columna) {
        Integer count = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM information_schema.columns
                WHERE table_name = 'DETALLE_TOMA_INVENTARIO'
                  AND column_name = ?
                """, Integer.class, columna.toUpperCase());
        return count != null && count > 0;
    }
}
